{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "argus-orchestrator.fullname" . }}-eso-secret
  labels:
    {{- include "argus-orchestrator.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecrets.clusterSecretStoreName }}
  target:
    name: {{ include "argus-orchestrator.fullname" . }}-eso-secret
    creationPolicy: Owner
  data:
    {{- range $k8sKey, $kvName := .Values.externalSecrets.keyMap }}
    - secretKey: {{ $k8sKey }}
      remoteRef:
        key: {{ $kvName }}
    {{- end }}
{{- end }}
