replicaCount: 1
image:
  repository: <YOUR_ACR>.azurecr.io/argus/testing_api_service
  tag: "dev-13fc08d"
  pullPolicy: Always
service:
  type: ClusterIP
  port: 8000
ingress:
  enabled: false
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
secrets:
  existingSecretName: argus-dev-secrets
extraEnv:
  TEST_RUNNER_URL: "http://test-runner.test-runner.svc.cluster.local:8000"
  ENVIRONMENT: "dev"
