[supervisord]
nodaemon=true
user=root

# [program:orchestrator]
# command=python -m google.adk.cli web --port 8080
# directory=/app
# autostart=false
# autorestart=false
# stdout_logfile=/dev/stdout
# stdout_logfile_maxbytes=0
# stderr_logfile=/dev/stderr
# stderr_logfile_maxbytes=0

[program:orchestrator_server]
command=python server.py
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
