apiVersion: v1
kind: Secret
metadata:
  name: {{ include "argus-demo-target.fullname" . }}-secret
  labels:
    {{- include "argus-demo-target.labels" . | nindent 4 }}
type: Opaque
stringData:
  AZURE_API_KEY: {{ .Values.secrets.azureApiKey | quote }}
  AZURE_API_BASE: {{ .Values.secrets.azureApiBase | quote }}
