"""Generate docs/probe-mapping.md — printed to stdout.

The doc used to be hand-written and drifted from what the code actually
computes: it counted one "primary" OWASP category per probe, while
`build_coverage` (the same function behind `GET /redteam/coverage` and
`argus-probe coverage`) counts every mapping a probe declares. Neither
number was wrong, but a public repo holding two contradictory coverage
tables is not something we can afford. This script is now the only source
of the doc; `orchestrator/tests/test_probe_mapping_doc_is_current.py`
fails if the checked-in file falls out of sync with it.

Usage (from orchestrator/):
    python scripts/gen_probe_mapping.py > ../docs/probe-mapping.md
"""

from __future__ import annotations

import sys
from pathlib import Path

# Run as a plain script (not `-m`), so Python only puts this file's own
# directory on sys.path. Add the service root (parent of this file's
# directory) so `orchestrator.redteam.*` resolves the same way it does under
# pytest (which is invoked as `python -m pytest` from that same directory).
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from orchestrator.redteam.coverage import OWASP_LLM_TOP10, build_coverage  # noqa: E402
from orchestrator.redteam.probe import load_all_probes  # noqa: E402

PROBES_DIR = Path(__file__).resolve().parent.parent / "orchestrator" / "redteam" / "probes"

_VALID_OWASP_IDS = frozenset(cell_id for cell_id, _name in OWASP_LLM_TOP10)

_STANDARD_LABELS = (
    ("owasp-llm-top10", "OWASP LLM Top 10"),
    ("mitre-atlas", "MITRE ATLAS"),
    ("nist-ai-rmf", "NIST AI RMF"),
    ("eu-ai-act", "EU AI Act"),
)


def invalid_owasp_ids(probes) -> list[tuple[str, str]]:
    """(probe_id, bad_id) for every probe declaring an OWASP id outside LLM01-LLM10.

    Such an id is silently dropped from the closed-universe OWASP cells in
    `build_coverage` — the run can only look less tested, never more, but a
    typo like `LLM011` would erase that probe's coverage with no signal.
    OWASP is the only standard checked here: ATLAS, NIST AI RMF and the EU AI
    Act are open-ended vocabularies with no fixed list to validate against.
    """
    return [
        (probe.id, owasp_id)
        for probe in probes
        for owasp_id in probe.mappings.owasp_llm
        if owasp_id not in _VALID_OWASP_IDS
    ]


def render(probes: list) -> str:
    coverage = build_coverage(probes)
    owasp_cells = coverage["standards"]["owasp-llm-top10"]["cells"]

    lines = []
    lines.append("# Probe -> Standards Mapping")
    lines.append("")
    lines.append(
        "Generated by `orchestrator/scripts/gen_probe_mapping.py` from `build_coverage` "
        "(the same function behind `GET /redteam/coverage` and `argus-probe coverage`). "
        "Do not hand-edit — regenerate with `python scripts/gen_probe_mapping.py > "
        "../docs/probe-mapping.md` from `orchestrator/`."
    )
    lines.append("")
    lines.append(
        "Counts below are **every mapping a probe declares**, not one \"primary\" category "
        "per probe. An earlier, hand-written version of this table counted one category per "
        "probe, which is why its numbers did not match what the code computes."
    )
    lines.append("")
    lines.append(f"`{len(probes)}` probes in the library.")
    lines.append("")
    lines.append("## OWASP LLM Top 10")
    lines.append("")
    lines.append("| OWASP | Category | Probes in library | Library status |")
    lines.append("|---|---|---:|---|")
    for cell in owasp_cells:
        lines.append(f"| {cell['id']} | {cell['name']} | {cell['probes_in_library']} | {cell['library_status']} |")
    lines.append("")
    lines.append("## Cells touched, per standard")
    lines.append("")
    lines.append("| Standard | Cells touched |")
    lines.append("|---|---:|")
    for key, label in _STANDARD_LABELS:
        cells = coverage["standards"][key]["cells"]
        touched = sum(1 for c in cells if c["probes_in_library"] > 0)
        lines.append(f"| {label} ({key}) | {touched} |")
    lines.append("")
    lines.append("## Probes")
    lines.append("")
    lines.append("| Probe ID | Attack class | Technique | Severity | Target class |")
    lines.append("|---|---|---|---|---|")
    for probe in sorted(probes, key=lambda p: p.id):
        attack_class = ",".join(probe.attack_class)
        technique = ",".join(probe.technique)
        target_class = ",".join(probe.target_class)
        lines.append(f"| `{probe.id}` | {attack_class} | {technique} | {probe.severity} | {target_class} |")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    probes = list(load_all_probes(PROBES_DIR))

    bad = invalid_owasp_ids(probes)
    if bad:
        print(f"WARNING: {len(bad)} probe(s) declare an OWASP id outside LLM01-LLM10:", file=sys.stderr)
        for probe_id, owasp_id in bad:
            print(f"  {probe_id}: {owasp_id!r}", file=sys.stderr)

    sys.stdout.write(render(probes))


if __name__ == "__main__":
    main()
