import os
import asyncio
import logging
import re
import json
import httpx
from dotenv import load_dotenv
from datetime import datetime
import uuid

# Configure logging
logger = logging.getLogger("OrchestratorAgent")
from google.adk.sessions import InMemorySessionService
from google.adk.runners import Runner
from google.genai import types # For creating message Content/Parts

from orchestrator.config import APP_NAME, USER_ID, SESSION_ID
from orchestrator.model_router import select_models

load_dotenv()

API_SERVICE_URL = os.getenv("API_SERVICE_URL", "http://argus-api-service.default.svc.cluster.local:8881")

async def save_script_to_db(filename: str, download_url: str, auth_token: str):
    if not auth_token:
        logger.warning("No auth token provided, skipping script save")
        return

    try:
        async with httpx.AsyncClient() as client:
            payload = {
                "name": filename,
                "script_address": download_url,
                "description": "Generated by ApiTestingAgent",
                "version": "1.0"
            }
            response = await client.post(
                f"{API_SERVICE_URL}/api/v1/scripts",
                json=payload,
                headers={"Authorization": auth_token}
            )
            if response.status_code in [200, 201]:
                logger.info(f"Successfully saved script {filename} to DB")
            else:
                logger.error(f"Failed to save script to DB: {response.status_code} {response.text}")
    except Exception as e:
        logger.error(f"Error saving script to DB: {e}")


def extract_script_content(text: str) -> str:
    """
    Extract Python script content from markdown code blocks or plain text.
    
    Args:
        text: The text containing script content
    
    Returns:
        Extracted script content or empty string if not found
    """
    if not text:
        return ""
    
    # Convert to string if it's not already
    text_str = str(text)
    
    # Try to extract from markdown code blocks (```python ... ```)
    python_code_pattern = r'```(?:python)?\s*\n(.*?)```'
    matches = re.findall(python_code_pattern, text_str, re.DOTALL)
    
    if matches:
        # Combine all code blocks
        script_content = '\n\n'.join(matches)
        logger.info(f"Extracted {len(matches)} Python code block(s)")
        return script_content.strip()
    
    # If no code blocks found, check if the entire text looks like Python code
    # (contains common Python keywords and patterns)
    python_indicators = ['import ', 'def ', 'class ', 'if __name__', 'pytest', 'test_', 'conftest']
    if any(indicator in text_str for indicator in python_indicators):
        logger.info("Text appears to contain Python code without markdown blocks")
        return text_str.strip()
    
    logger.info("No Python script content detected")
    return ""



async def stream_test_strategy(source_content: str, context: dict = None, session_id: str = None, user_id: str = None, local_test_enabled: bool = False, remote_test_enabled: bool = False, auth_token: str = None, ssh_config: dict = None, cdp_url: str = None, wizard_state: dict = None):
    """
    Generator function to stream events from the test strategy creation process.
    """
    # Use provided IDs or fall back to defaults/random
    effective_user_id = user_id or USER_ID
    effective_session_id = session_id or SESSION_ID

    # Initialize session service
    session_service = InMemorySessionService()

    # Prepare context with local test configuration
    if context is None:
        context = {}
    else:
        if not isinstance(context, dict):
            context = dict(context)

    # Add local test configuration to context
    context["local_test_enabled"] = local_test_enabled
    context["user_id"] = effective_user_id
    context["auth_token"] = auth_token

    # Add remote test execution config
    if ssh_config:
        context["ssh_config"] = ssh_config
        context["remote_test_enabled"] = True
        logger.info("SSH config provided — remote test execution enabled")
    elif remote_test_enabled:
        context["remote_test_enabled"] = True
        logger.info("Remote test execution enabled via test-runner service")

    # Add CDP URL for local Chrome remote debugging
    if cdp_url:
        context["cdp_url"] = cdp_url
        logger.info(f"CDP URL provided — will connect to local Chrome at {cdp_url}")

    # Wizard state threading — planner reads ctx.session.state["wizard_state"]
    context["wizard_state"] = wizard_state

    # Smart model routing based on subscription plan
    plan = context.get("subscription_plan", "free")
    model_selection = select_models(plan, source_content)
    context["browser_model"] = model_selection["browser_model"]
    context["script_model"] = model_selection["script_model"]
    context["routing_reason"] = model_selection["routing_reason"]
    logger.info(f"Model routing: plan={plan}, browser={model_selection['browser_model']}, "
                f"script={model_selection['script_model']}, reason={model_selection['routing_reason']}")

    # Create session with state
    session = await session_service.create_session(
        app_name=APP_NAME,
        user_id=effective_user_id,
        session_id=effective_session_id,
        state=context  # Pass context as session state
    )

    from orchestrator.planner.agent import PlannerAgent
    dynamic_root_agent = PlannerAgent(name="PlannerAgent")
    logger.info("🤖 Using PlannerAgent (Opus 4.7 ReAct) as root")

    # Create runner
    runner = Runner(
        agent=dynamic_root_agent,
        app_name=APP_NAME,
        session_service=session_service
    )

    # Prepare input message — the planner reads execution flags from
    # ctx.session.state directly (see PlannerAgent._build_user_message), so we
    # pass only the raw user-supplied target here. Legacy SmartPipeline
    # "generate a test strategy document" framing was removed because it
    # biased the planner toward doc-generation instead of test execution.
    input_message = f"Testing target: {source_content}"
    
    logger.info("=" * 80)
    logger.info("📝 SENDING INPUT TO PLANNER AGENT (stream_test_strategy)")
    logger.info(f"User ID: {effective_user_id}")
    logger.info(f"Session ID: {effective_session_id}")
    logger.info(f"Source Content: {source_content[:200]}..." if len(source_content) > 200 else f"Source Content: {source_content}")
    logger.info(f"Context: {context}")
    logger.info(f"Full Input Message:\n{input_message}")
    logger.info("=" * 80)

    # Run the complete system
    # Initialize script_url variable before the loop
    script_url = None

    # Run the complete system
    try:
        async with runner:
            async for event in runner.run_async(
                user_id=effective_user_id,
                session_id=effective_session_id,
                new_message=types.Content(
                    role='user',
                    parts=[types.Part.from_text(text=input_message)]
                )
            ):
                # Log the raw event for debugging
                logger.info(f"🔔 Received event from runner: type={type(event).__name__}")
                # logger.info(f"   Event attributes: {dir(event)}")
                # logger.info(f"   Event dict: {event.__dict__ if hasattr(event, '__dict__') else 'N/A'}")
                
                # Check for artifact or ssh_result event from ApiTestingAgent
                if hasattr(event, 'author') and event.author == "ApiTestingAgent":
                    if hasattr(event, 'content') and event.content and hasattr(event.content, 'parts'):
                        for part in event.content.parts:
                            if hasattr(part, 'text') and part.text:
                                try:
                                    text_content = part.text
                                    if text_content.strip().startswith('{'):
                                        data = json.loads(text_content)
                                        if data.get("type") == "artifacts":
                                            files = data.get("files", [])
                                            for file_info in files:
                                                filename = file_info.get("filename")
                                                download_url = file_info.get("download_url")
                                                if filename and download_url:
                                                    logger.info(f"Found artifact: {filename}, capturing script URL...")
                                                    # Capture the URL for the final result
                                                    script_url = download_url

                                                    # Yield event for frontend to handle saving
                                                    yield {
                                                        "type": "artifact",
                                                        "script_url": download_url,
                                                        "filename": filename
                                                    }
                                        elif data.get("type") == "ssh_result":
                                            logger.info(f"SSH execution result received (exit_code={data.get('ssh_result', {}).get('exit_code')})")
                                            yield data  # Pass through as-is to orchestrator/frontend
                                except json.JSONDecodeError:
                                    pass
                                except Exception as e:
                                    logger.error(f"Error processing artifact event: {e}")

                # Yield the raw event or a processed version of it
                # For now, let's yield a dictionary representation if possible, or just the event object
                # The caller will handle serialization
                yield event

        if script_url:
            logger.info(f"✅ Using script URL capture from agent: {script_url}")

        yield {
            "type": "result",
            "success": True,
            "response": "Processing complete",
            "script_url": script_url,
            "generated_content": {},
        }

    except Exception as e:
        import traceback
        tb_str = traceback.format_exc()
        logger.error(f"Error in stream_test_strategy: {e}\n{tb_str}")
        yield {
            "type": "error",
            "success": False,
            "error": str(e)
        }


async def create_test_strategy(source_content: str, context: dict = None, session_id: str = None, user_id: str = None, local_test_enabled: bool = False):
    """
    Main function to analyze user requirements and create test strategy from source material
    """

    # Use provided IDs or fall back to defaults/random
    effective_user_id = user_id or USER_ID
    effective_session_id = session_id or SESSION_ID

    # Initialize session service
    session_service = InMemorySessionService()

    # Prepare context with local test configuration
    if context is None:
        context = {}
    
    # Add local test configuration to context
    context["local_test_enabled"] = local_test_enabled
    context["user_id"] = effective_user_id

    # Create session with state
    session = await session_service.create_session(
        app_name=APP_NAME,
        user_id=effective_user_id,
        session_id=effective_session_id,
        state=context  # Pass context as session state
    )

    from orchestrator.planner.agent import PlannerAgent
    dynamic_root_agent = PlannerAgent(name="PlannerAgent")
    logger.info("🤖 Using PlannerAgent (Opus 4.7 ReAct) as root")

    # Create runner
    runner = Runner(
        agent=dynamic_root_agent,
        app_name=APP_NAME,
        session_service=session_service
    )

    # Prepare input message — the planner reads execution flags from
    # ctx.session.state directly (see PlannerAgent._build_user_message), so we
    # pass only the raw user-supplied target here. Legacy SmartPipeline
    # "generate a test strategy document" framing was removed because it
    # biased the planner toward doc-generation instead of test execution.
    input_message = f"Testing target: {source_content}"

    # Run the complete system
    try:
        async with runner:
            async for event in runner.run_async(
                user_id=effective_user_id,
                session_id=effective_session_id,
                new_message=types.Content(
                    role='user',
                    parts=[types.Part.from_text(text=input_message)]
                )
            ):
                print(f"Event received: {event}")

            print("✅ Test strategy creation completed successfully!")
            
            return {
                "success": True,
                "response": "Processing complete",
                "generated_content": {},
            }

    except Exception as e:
        print(f"❌ Error creating test strategy: {e}")
        return {
            "success": False,
            "error": str(e)
        }


async def main():

    content = """
    Introduction to Software Quality Assurance

    Software Quality Assurance (QA) is a systematic process ensuring that software products meet specified requirements and quality standards. It extends beyond simple error detection to focus on defect prevention and ensuring user satisfaction throughout the development lifecycle.

    Key Concepts:

    Functional Testing: Verifies that the software functions according to business requirements and logic.

    Non-Functional Testing: Assesses attributes such as Performance (speed/load), Security (vulnerabilities), and Usability.

    Regression Testing: Ensures that recent code changes or new features have not adversely affected existing functionalities.

    Automation vs Manual: Distinguishing between tests that require human intuition and repetitive tasks suitable for scripts.

    Common techniques include Boundary Value Analysis, Equivalence Partitioning, API Testing, and Integration Testing. Artifacts usually include Test Plans, Test Cases, and Bug Reports.

    The QA process involves Requirement Analysis, Test Planning, Test Case Design, Environment Setup, Test Execution, and Defect Reporting. Success depends on clear requirements coverage, early bug detection, and effective risk management.

    IMPORTANT: We must perform rigorous API Testing on the backend services. Verify all REST endpoints for status codes and payload validity.
    
    Instruction: Based on the concepts above, analyze the user's input to identify what type of testing is needed, specific test scenarios (including edge cases), and the appropriate testing technique.
    """

    # Context for content creation corresponding to Software Quality Assurance content
    context = {
        "audience": "QA",
        "topic": "Software Quality Assurance",
        "learning_objectives": [
            "Understand the basic principles of software quality assurance",
            "Differentiate between functional and non-functional testing",
            "Recognize the QA process phases (Requirement Analysis, Test Planning, etc.)",
            "Identify key testing techniques and artifacts"
        ]
    }

    # Create learning content
    result = await create_test_strategy(content, context)

    if result["success"]:
        print("\n✅ CONTENT CREATION COMPLETED!")
        print("\n📊 Generated Content Summary:")

        print(f"\n📝 Final Response: {result['response']}")

    else:
        print(f"\n❌ Content creation failed: {result['error']}")

if __name__ == "__main__":
    asyncio.run(main())
