"""argus-probe init subcommand: scaffold a target.json + optional GH Action workflow."""
from __future__ import annotations

import json
from pathlib import Path

import click

from argus_probe.target_loader import _KNOWN_KINDS

# Per-kind question definitions. Each tuple: (field_name, prompt_text, default_or_None)
_KIND_QUESTIONS: dict[str, list[tuple[str, str, str | None]]] = {
    "openai_compat": [
        ("endpoint_url", "Endpoint URL", "https://api.openai.com/v1/chat/completions"),
        ("model", "Model name", None),
        ("api_key_env", "API key env var", "OPENAI_API_KEY"),
    ],
    "anthropic_native": [
        ("model", "Model name", "claude-haiku-4-5-20251001"),
        ("api_key_env", "API key env var", "ANTHROPIC_API_KEY"),
    ],
    "custom_http": [
        ("request_url", "Request URL", None),
        ("request_body_template", "Request body template (Jinja2 with {{prompt}})",
         '{"input": {{prompt|tojson}}}'),
        ("response_jsonpath", "Response JSONPath", "$.output"),
    ],
    "grpc": [
        ("endpoint", "Endpoint (host:port)", "localhost:50051"),
        ("service_method", "Service method (pkg.Service/Method)", None),
        ("prompt_field", "Prompt field name", "user_input"),
        ("response_field", "Response field name", "response"),
    ],
    "browser_use": [
        ("agent_url", "Browser-using agent URL", None),
        ("scenario_kind", "Scenario kind (dom_injection/ui_phishing/visual_injection/os_cmd)", "dom_injection"),
    ],
    "payment_agent": [
        ("testbed_url", "Payment testbed URL", "http://127.0.0.1:8090"),
        (
            "inner_json",
            "Inner target spec (JSON) for the transport that talks to your agent",
            '{"kind": "openai_compat", "endpoint_url": "http://127.0.0.1:8091/v1/chat/completions", "model": "argus-demo-payment-agent"}',
        ),
    ],
    "mcp_agent": [
        ("testbed_url", "MCP testbed URL", "http://127.0.0.1:8092"),
        (
            "inner_json",
            "Inner target spec (JSON) for the transport that talks to your agent",
            '{"kind": "openai_compat", "endpoint_url": "http://127.0.0.1:8093/v1/chat/completions", "model": "argus-demo-mcp-agent"}',
        ),
    ],
    "http_upload": [
        ("upload_url", "Upload URL", None),
        ("upload_field_name", "Upload form field name", "file"),
        ("upload_filename", "Upload filename", "payload.svg"),
        ("upload_content_type", "Upload content type", "image/svg+xml"),
        ("render_url_jsonpath", "Render URL JSONPath (extracts the render URL from the upload response)", "$.url"),
    ],
}

_WORKFLOW_TEMPLATE = """\
# .github/workflows/argus-probe.yml
# Generated by `argus-probe init`. Customize as needed.
name: argus-probe
on:
  schedule:
    # Weekly Monday 06:00 UTC
    - cron: '0 6 * * 1'
  workflow_dispatch: {{}}

jobs:
  redteam:
    uses: <your-gh-user>/argus-probe-action/.github/workflows/argus-probe-reusable.yml@v1
    with:
      target-config: {target_path}
      threshold: warn
      per-run-cap: '0.50'
    secrets:
      api-token: ${{{{ secrets.ARGUS_API_TOKEN }}}}
"""


@click.command("init")
@click.option(
    "--kind",
    required=True,
    type=click.Choice(sorted(_KNOWN_KINDS)),
    help="Target adapter kind",
)
@click.option(
    "--output",
    default="argus-target.json",
    show_default=True,
    help="Output target.json path",
)
@click.option(
    "--workflow/--no-workflow",
    default=None,
    help="Generate .github/workflows/argus-probe.yml (prompts if neither flag given)",
)
def init_command(kind: str, output: str, workflow: bool | None) -> None:
    """Generate a target.json (and optional GitHub Action workflow) for Argus."""
    click.echo(f"Argus target initializer")
    click.echo(f"Target kind: {kind}")
    questions = _KIND_QUESTIONS[kind]

    spec: dict[str, object] = {"kind": kind}
    for field, prompt_text, default in questions:
        if default is not None:
            value = click.prompt(prompt_text, default=default, show_default=True)
        else:
            value = click.prompt(prompt_text)
        spec[field] = value

    # api_key_env → api_key (CLI run command resolves $-vars at runtime)
    if "api_key_env" in spec:
        env_var = spec.pop("api_key_env")
        spec["api_key"] = "${" + str(env_var) + "}"

    # inner_json → inner (payment_agent / mcp_agent nest another target spec
    # for the transport that actually talks to the agent)
    if "inner_json" in spec:
        raw_inner = spec.pop("inner_json")
        try:
            spec["inner"] = json.loads(str(raw_inner))
        except json.JSONDecodeError as exc:
            raise click.UsageError(f"inner target spec is not valid JSON: {exc}") from exc

    # sandbox is a safety interlock, not a question: payment_agent and
    # mcp_agent drive an agent that spends money / reaches a live MCP server,
    # and both api_service and the CLI loader refuse a spec without
    # sandbox: true — there is no way to turn it off, so it must never be
    # presented as something a user could answer "no" to.
    if kind in ("payment_agent", "mcp_agent"):
        spec["sandbox"] = True

    # Confirm-overwrite if target file exists
    target_path = Path(output)
    if target_path.exists():
        if not click.confirm(f"{output} exists. Overwrite?", default=False):
            raise click.Abort()

    target_path.write_text(json.dumps(spec, indent=2) + "\n")
    click.echo(f"✅ Wrote {target_path}")

    # Workflow file
    if workflow is None:
        workflow = click.confirm("Generate GitHub Action workflow?", default=False)
    if workflow:
        wf_path = Path(".github/workflows/argus-probe.yml")
        wf_path.parent.mkdir(parents=True, exist_ok=True)
        wf_path.write_text(_WORKFLOW_TEMPLATE.format(target_path=target_path.name))
        click.echo(f"✅ Wrote {wf_path}")

    click.echo("")
    click.echo(f"Next: argus-probe run --target {target_path.name}")
    click.echo("Add ARGUS_API_TOKEN to your CI secrets to enable scheduled runs.")
